---
location: rack-3
id: 4
ports:
  0: 
    interface: 'fastethernet0/0'
    description: 'Lien PE2-P1'
    ip_address:  10.1.0.10
    mask:     255.255.255.252
    subnet:     10.1.0.8
    mask_ospf:  3
    area:   0
    mpls: 'yes'
  1: 
    interface: 'fastethernet0/1'
    description: 'Lien PE2-P2'
    ip_address:  10.1.0.14
    mask:     255.255.255.252
    subnet:     10.1.0.12
    mask_ospf:  3
    area:   0
    mpls: 'yes'
  2: 
    interface: 'loopback0'
    description: 'Loopback0'
    ip_address:  4.4.4.4
    mask:     255.255.255.255
    subnet:     4.4.4.4
    mask_ospf:  0
    area:   4