---
- hosts: ios
  gather_facts: no
  tasks:
  - raw: "show version"
    register: show
  - debug: var=show.stdout_lines
 
- hosts: qfx
  gather_facts: no
  tasks:
  - raw: "show ethernet-switching table"
 